### ISSUE TITLE
co_await on linux

### ISSUE THREAD

**Issue by unicomp21** [jimspr/awaituv#6]
Is there any way to use co_await when targetting linux w/ VC++?

**Comment by jimspr** [comment]
Our compiler only targets windows. There is a branch of clang that supports co_await. https://github.com/GorNishanov/clang/tree/snapshot-20170130

**Comment by jhugard** [comment]
Just a note, coroutines have been pulled into the master branch of clang; e.g., see [this commit](https://github.com/llvm-mirror/clang/commit/37a1cf7528130751151a50d8ecdeb370da3539e2)

**Comment by unicomp21** [comment]
Awesome!

**Comment by jimspr** [comment]
Yes, this is great to see. I am still working on this as part of a larger project and getting Clang support in the master branch will make things much easier.

**Comment by unicomp21** [comment]
Are there plans for VC++ to support co_await on linux?

**Comment by unicomp21** [comment]
Or are we better off using fibers?

**Comment by unicomp21** [comment]
@jimspr ^^ any updates on the linux target?  Any plans for webassembly?
