### ISSUE TITLE
Those RAII types like fs_t are dangerous

### ISSUE THREAD

**Issue by CarterLi** [jimspr/awaituv#8]
Consider following code:

```c++
{
  fs_t req; // Free uninitialized pointers
}

{
  fs_t req;
  uv_fs_open(loop, &req, ...); // init req
  return req; // Req is copied, which results in req being freed twice
}
```

The second possibility is rather harder to found because compilers may apply NRVO ( but not always true).

In order to make `fs_t` safe to use, you have to initialize `fs_t` always ( for example memset(0) ) and make it non-copyable ( movable only ). I'd rather suggest not defining these types in global headers. Move them to samples and let users choose.

**Comment by jimspr** [comment]
Just fixed this to initialize to zero and prevent copy. Move was already prevented due to dtor.
